// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAfFBFWu6DBLChKVZ30opP4L7z2vra1dA',
    appId: '1:181125991671:web:fcf82bea37442181c597f2',
    messagingSenderId: '181125991671',
    projectId: 'benim-kulturum',
    authDomain: 'benim-kulturum.firebaseapp.com',
    storageBucket: 'benim-kulturum.firebasestorage.app',
    measurementId: 'G-STEFNE2VB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTznlKrR7e93gSPHKMWRE4CxTqj0tXNGY',
    appId: '1:181125991671:android:5d340021319cc6e8c597f2',
    messagingSenderId: '181125991671',
    projectId: 'benim-kulturum',
    storageBucket: 'benim-kulturum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQhAchwpqyvnyCD5BN586i5D4J1kPbiNA',
    appId: '1:181125991671:ios:c26a751c77d37610c597f2',
    messagingSenderId: '181125991671',
    projectId: 'benim-kulturum',
    storageBucket: 'benim-kulturum.firebasestorage.app',
    iosBundleId: 'com.example.benimKulturumV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQhAchwpqyvnyCD5BN586i5D4J1kPbiNA',
    appId: '1:181125991671:ios:c26a751c77d37610c597f2',
    messagingSenderId: '181125991671',
    projectId: 'benim-kulturum',
    storageBucket: 'benim-kulturum.firebasestorage.app',
    iosBundleId: 'com.example.benimKulturumV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAfFBFWu6DBLChKVZ30opP4L7z2vra1dA',
    appId: '1:181125991671:web:4fadfda74e93cae7c597f2',
    messagingSenderId: '181125991671',
    projectId: 'benim-kulturum',
    authDomain: 'benim-kulturum.firebaseapp.com',
    storageBucket: 'benim-kulturum.firebasestorage.app',
    measurementId: 'G-PXZ9BLQ241',
  );
}
